ClickHouse/clickhouse-cpp

clickhouse/base/output.cpp
That could happen when socket is closed by timeout or connection loss,
at this point there is no sence in trying to resend buffered data
and usually no reliable way of detecting and handling that through all
abstractions. So the exception is ignored.
=> Fixed exception thrown from BufferedOutput's destructor

clickhouse/base/compressed.cpp, clickhouse/client.cpp, clickhouse/columns/factory.cpp, clickhouse/columns/nullable.cpp, clickhouse/columns/uuid.cpp, tests/simple/main.cpp
Seems like gcc's version 10 will be quite strict about missing headers (Our RClickhouse package is build on top of this c++ lib: https://www.stats.ox.ac.uk/pub/bdr/gcc10/RClickhouse.log). Therefore, I just added the required stdexcept headers.
=> gcc-10 compliance

clickhouse/columns/itemview.h
The library doesn't compile with GCC 10
=> Add missing header

clickhouse/client.cpp, clickhouse/client.h
try to reconnect send_retries times before throw in RetryGuard (artpul#112)
See  https://github.com/artpaul/clickhouse-cpp/pull/112
=> Cherry-pick https://github.com/artpaul/clickhouse-cpp/pull/112 

clickhouse/client.cpp, clickhouse/client.h, clickhouse/columns/factory.cpp, clickhouse/types/type_parser.cpp, clickhouse/types/type_parser.h, ut/client_ut.cpp, ut/columns_ut.cpp, ut/type_parser_ut.cpp
Columns of `SimpleAggregateFunction(func, X)` are now handled properly and can be read from client's code as Column-`X`.
=> Implemented reading values of SimpleAggregateFunction

clickhouse/columns/column.h, clickhouse/columns/lowcardinality.cpp, clickhouse/columns/lowcardinality.h, ut/client_ut.cpp, ut/columns_ut.cpp
Now `ColumnLowCardinality`-column can be safely reused after being cleared.
Added unit-tests and integration tests to validate fix.
=> Fixed `ColumnLowCardinality::Clear()` 

.gitignore, README.md, clickhouse/columns/date.cpp, clickhouse/columns/date.h, clickhouse/columns/decimal.cpp, clickhouse/columns/decimal.h, clickhouse/columns/factory.cpp, clickhouse/columns/itemview.cpp, clickhouse/columns/numeric.cpp, clickhouse/columns/numeric.h, clickhouse/types/type_parser.cpp, clickhouse/types/types.cpp, clickhouse/types/types.h, tests/simple/main.cpp, ut/client_ut.cpp, ut/columns_ut.cpp, ut/performance_tests.cpp
Based on #38 
New Column type: `ColumnDateTime64`
Sligtly updated some underlying code
Added unit and integrration tests for ColumnDateTime64
Closes #38
=> Add DateTime64 data type.

clickhouse/columns/lowcardinality.cpp, ut/columns_ut.cpp
Fix of empty string becoming a first non-empty string of ColumnLowCardinality;
Added some tests to make sure that doesn't happen again.
=> Fix of LowCardinality bug: empty string converted to other value on INSERT

clickhouse/columns/string.cpp, clickhouse/columns/string.h, ut/columns_ut.cpp
Similar to #59, but more ClickHouse - way: strings that are smaller are padded with zeroes, larger strings cause an exception (https://clickhouse.tech/docs/en/sql-reference/data-types/fixedstring/)
Closes #59
=> FixedString::Append checks

README.md, clickhouse/client.cpp, clickhouse/columns/date.cpp, clickhouse/columns/date.h, clickhouse/columns/factory.cpp, clickhouse/types/type_parser.cpp, clickhouse/types/type_parser.h, clickhouse/types/types.cpp, clickhouse/types/types.h, tests/simple/main.cpp, ut/client_ut.cpp, ut/columns_ut.cpp, ut/type_parser_ut.cpp, ut/types_ut.cpp
Backport https://github.com/artpaul/clickhouse-cpp/pull/120
As is, lot of unresolved conflicts.
=> Timezone support for DateTime

clickhouse/base/compressed.cpp, clickhouse/client.cpp, contrib/lz4/LICENSE, contrib/lz4/lz4.c, contrib/lz4/lz4.h, contrib/lz4/lz4hc.c, contrib/lz4/lz4hc.h
Updated LZ4 version 1.9.2 for significant performance improvements.
https://github.com/lz4/lz4/tree/v1.9.2
https://github.com/lz4/lz4/tree/r131
According the links above, the performance increases 2x decompression.
=> Updated LZ4 version 1.9.2

clickhouse/base/socket.cpp, clickhouse/base/socket.h, clickhouse/client.cpp, clickhouse/client.h
During benchmark, I found there are significant delay when the block is smaller than the buffer size (defaults to 8192 bytes).
Test program:
``` cpp
#include <clickhouse/client.h>
#include <cstdlib>
#include <chrono>
#include <iostream>
using namespace clickhouse;
int main(int argc, char **argv)
{
Client client(ClientOptions().SetHost("localhost").SetPassword("qwerty"));
client.Execute("CREATE TABLE IF NOT EXISTS test.delay (id UInt8) ENGINE = Memory");
int count = atoi(argv[1]); // count
for (int i = 0; i < 10; i++) {
Block block;
auto id = std::make_shared<ColumnUInt8>();
for (int j = 0; j < count; j++) {
id->Append(65);
}
block.AppendColumn("id"  , id);
auto start = std::chrono::steady_clock::now();
client.Insert("test.delay", block);
auto end = std::chrono::steady_clock::now(); …
```
=> Add TCP_NODELAY option

clickhouse/base/socket.cpp
`setsockopt` on Windows has slightly different signature.
=> Fix TCP_NODELAY in Windows

clickhouse/columns/date.cpp, clickhouse/columns/decimal.cpp, clickhouse/columns/itemview.cpp, clickhouse/columns/itemview.h, clickhouse/types/types.h, ut/CMakeLists.txt, ut/columns_ut.cpp, ut/itemview_ut.cpp
Fixed multiple compile-time issues using `absl::int128` as `clickhouse::Int128`
Fixed storing `Int128` value to `ItemView`
Added tests:
* Basic cases for `Int128` numeric columns
* Parsing `Decimal128` values from a string (basic and with overflow)
* `ItemView` construction tests (both positive and negative cases)
Known limitations:
* Overflow checks are broken for std::numeric_limits<Int128>::min() when there is no __int128.
Closes: #73 
Closes: #72
=> Fixes #66  to allow using absl::int128 as Int128

clickhouse/CMakeLists.txt, clickhouse/client.cpp, clickhouse/client.h, clickhouse/columns/factory.cpp, clickhouse/columns/factory.h, clickhouse/columns/lowcardinality.h, clickhouse/columns/lowcardinalityadaptor.h, ut/client_ut.cpp, ut/columns_ut.cpp
Ease migration of the old codebases, which can't afford to switch to using ColumnLowCardinalityT or ColumnLowCardinality directly, but still want to benefit from smaller on-wire LowCardinality bandwidth footprint.
Please [see test](https://github.com/ClickHouse/clickhouse-cpp/compare/master...Enmk:LowCardinality_as_wrapped_column?expand=1#diff-d72200167c0e04ada10b43afbfed7c51247357076f27386ca07b4be7a876a7deR240) for details.
=> Allow users to explicitly access LowCardinality<WrappedColumn> columns as WrappedColumn

CMakeLists.txt, clickhouse/CMakeLists.txt, clickhouse/columns/date.cpp, clickhouse/columns/decimal.cpp, clickhouse/columns/itemview.cpp, clickhouse/columns/itemview.h, clickhouse/columns/numeric.h, clickhouse/types/types.h, contrib/absl/CMakeLists.txt, contrib/absl/base/attributes.h, contrib/absl/base/config.h, contrib/absl/base/internal/bits.h, contrib/absl/base/macros.h, contrib/absl/base/optimization.h, contrib/absl/base/options.h, contrib/absl/base/policy_checks.h, contrib/absl/base/port.h, contrib/absl/numeric/int128.cc, contrib/absl/numeric/int128.h, contrib/absl/numeric/int128_have_intrinsic.inc, contrib/absl/numeric/int128_no_intrinsic.inc, ut/CMakeLists.txt, ut/columns_ut.cpp, ut/itemview_ut.cpp
Backport 
https://github.com/artpaul/clickhouse-cpp/pull/119
See
https://github.com/artpaul/clickhouse-cpp/issues/113
https://github.com/artpaul/clickhouse-cpp/issues/116
=> use absl for int128

clickhouse/columns/array.cpp, clickhouse/columns/array.h, clickhouse/columns/column.h, clickhouse/columns/date.cpp, clickhouse/columns/date.h, clickhouse/columns/decimal.cpp, clickhouse/columns/decimal.h, clickhouse/columns/enum.cpp, clickhouse/columns/enum.h, clickhouse/columns/ip4.cpp, clickhouse/columns/ip4.h, clickhouse/columns/ip6.cpp, clickhouse/columns/ip6.h, clickhouse/columns/lowcardinality.cpp, clickhouse/columns/lowcardinality.h, clickhouse/columns/nothing.h, clickhouse/columns/nullable.cpp, clickhouse/columns/nullable.h, clickhouse/columns/numeric.cpp, clickhouse/columns/numeric.h, clickhouse/columns/string.cpp, clickhouse/columns/string.h, clickhouse/columns/tuple.h, clickhouse/columns/uuid.cpp, clickhouse/columns/uuid.h
Column::Slice() is now a const-method.
Updated all descendants of Column.
=> Minor (backward compatitable) API improvement

clickhouse/columns/factory.cpp, clickhouse/types/type_parser.cpp, clickhouse/types/types.h, ut/columns_ut.cpp
Fixed bug of not being able to create Int128 from type name string.
Added test to ensure that users can create Int128 and UUID columns.
=> Ensure that users can create Int128 and UUID columns

clickhouse/CMakeLists.txt
=> Remove installation of previously removed `base/coded.h` header

.github/workflows/linux.yml, .github/workflows/linux_ssl.yml, .github/workflows/macos.yml, .github/workflows/macos_ssl.yml, ut/ssl_ut.cpp
Assuming OpenSSL from Homebrew is installed.
=> Allow macOS builds to compile and run SSL tests

clickhouse/columns/decimal.cpp
On the MSVC compiler I had a compilation problem in this section of code. The problem was that `std::signbit` was only used for floats, but part of the code used this function for ints. 
The compiler error was ` Error C2668: 'signbit': ambiguous overloaded function call'.
The compiler version is 19.29
=> Fix for MSVC compilation

.github/workflows/linux.yml, CMakeLists.txt, clickhouse/base/sslsocket.cpp
* Added GCC-8 and GCC-9 builds on linux in CI/CD
* Fixed build on GCC-8
* Minor fixes and comments
=> GCC-8 support fix

.github/workflows/macos_ssl.yml
Setting OPENSSL_ROOT_DIR to a directory where brew usually installs openssl
=> CI/CD: fixing  MacOS OpenSSL variant

.github/workflows/windows_msvc.yml, clickhouse/base/compressed.cpp, clickhouse/base/platform.h, clickhouse/base/socket.cpp, clickhouse/base/socket.h, clickhouse/client.cpp, clickhouse/columns/decimal.cpp, tests/simple/CMakeLists.txt, ut/CMakeLists.txt, ut/columns_ut.cpp, ut/readonly_client_test.cpp, ut/tcp_server.cpp, ut/utils.h
* github action for msvc added. Closes #130
* there is an issue with dynamic linking & DLL paths when compiling tests. I've switched tests to static linking
* added tls offoader proxy for windows tests, mimicking local clickhouse by tunneling the queries to a cloud instance of clickhouse
* get proper status codes via WSAGetLastError for windows, fixes #127 
Known issues:
- no support for secure connections (need to reimplement secure_socket with sspi.h and other windows thing). Maybe can work with openssl (not tested).
- there are some warnings at compile time
=> Add support for MSVC

clickhouse/columns/tuple.cpp, clickhouse/columns/tuple.h, ut/columns_ut.cpp
This closes #115 and also adds the option to Append Tuples to ```ColumnTuples```.
=> Implement Append for ColumnTuple

clickhouse/columns/ip4.cpp, clickhouse/columns/ip4.h, clickhouse/columns/ip6.cpp, clickhouse/columns/ip6.h, clickhouse/columns/nothing.h, tests/simple/main.cpp, ut/columns_ut.cpp, ut/performance_tests.cpp
Added tests, simplified implementation + few extra minor touches
Closes: #101, #88
=> Fixed ColumnIPv4::Append()

clickhouse/base/sslsocket.cpp, clickhouse/base/sslsocket.h, clickhouse/client.cpp, clickhouse/client.h, tests/simple/CMakeLists.txt, tests/simple/main.cpp, ut/client_ut.cpp, ut/connection_failed_client_test.cpp, ut/connection_failed_client_test.h, ut/ssl_ut.cpp, ut/utils.cpp, ut/utils.h
Added ClientOptions:
- skip_verification - to skip all verification
- host_flags - to set hostname verification mode
- configuration - to configure SSL connection
Updated and refactored tests.
Updated tests/simple/main.cpp to reuse so utility code from unit-tests.
Closes: #142
=> OpenSSL updates: allow to configure or skip verification

clickhouse/types/types.cpp, clickhouse/types/types.h, ut/types_ut.cpp
Performance improvement for `Type:IsEqual()`:
- it shortcuts for completely different types.
- should now be much more performant for simple types
- executes `Type::GetName()` about 1 time per type
For complex types, `Type::IsEqual()` relies on computing hash of the `Type::GetName()`, that hash is computed at least once and reused later.
In the worst case, name is generated multiple times by multiple threads if they manage to hit the same spot of the code at the same time.
According to (a quite synthetic) tests, new implementation is about ~150 times faster:
```c++
const std::string type_names[] = {
"UInt8",
"Int8",
"UInt128",
"String",
"FixedString(0)",
"FixedString(10000)",
"DateTime('UTC')",
"DateTime64(3, 'UTC')",
"Decimal(9,3)",
"Decimal(18,3)",
"Enum8()",
"Enum16()",
"Enum8('ONE' = …
```
=> Better performance for Type::IsEqual()

clickhouse/columns/itemview.h
Submitted on behalf of a third-party: Yandex N.V.
=> replace explicit string_view initialization from {nullptr, 0} with default ctor

clickhouse/CMakeLists.txt
Do not link with gcc & libstdc++ support libraries when going with clang & libc++.
Signed-off-by: David Keller <david@woorton.com>
=> Fix build on clang & libc++

clickhouse/columns/array.cpp, ut/column_array_ut.cpp
Data is copied exactly once, instead of `2*M*N`, where:
* N is number of rows in slice
* M is size of nested array
=> Optimized ColumnArray::Slice

clickhouse/columns/date.cpp, ut/CMakeLists.txt, ut/Column_ut.cpp, ut/CreateColumnByType_ut.cpp, ut/client_ut.cpp, ut/columns_ut.cpp, ut/performance_tests.cpp, ut/utils.cpp, ut/utils.h, ut/utils_comparison.h, ut/utils_meta.h, ut/utils_performance.h, ut/value_generators.cpp, ut/value_generators.h
- Added a set of generic tests that validate general API for `Column` subclass, see `ut/Column_ut.cpp`
- moved tests around to simplify `ut/columns_ut.cpp`
- moved utility code around to simplify `ut/utils.h`
- fixed bug in `ColumnDateTime::CloneEmpty`
=> Test refactoring

ut/array_of_low_cardinality_tests.cpp
In https://github.com/ClickHouse/clickhouse-cpp/issues/178 was reported that empty arrays in LC(Array) was crashing the client. This PR adds empty arrays to the existing unit test.
Not closing the issue because I am waiting for more OP information.
=> Add empty arrays to LC(Array) existing unit test

clickhouse/columns/date.cpp, clickhouse/columns/decimal.cpp, clickhouse/columns/ip4.cpp, clickhouse/columns/ip6.cpp, clickhouse/columns/itemview.cpp, clickhouse/columns/itemview.h, clickhouse/columns/uuid.cpp, clickhouse/types/types.cpp, clickhouse/types/types.h, ut/Column_ut.cpp, ut/itemview_ut.cpp
- Added test to verify `GetItem` implementation
- Fixed various issues in `GetItem` implementations
- Fixed `ItemView` size checks for `IPv6` and `Decimal`
=> Tests for Column::GetItem

clickhouse/columns/enum.cpp, clickhouse/columns/enum.h, clickhouse/types/types.cpp, clickhouse/types/types.h
Storing only one copy of the value name.
=> Better ColumnEnum - less memory

ut/CMakeLists.txt, ut/Column_ut.cpp, ut/array_of_low_cardinality_tests.cpp, ut/client_ut.cpp, ut/roundtrip_column.cpp, ut/roundtrip_column.h, ut/utils.cpp, ut/utils.h, ut/value_generators.h
Roundtrip column values to server in generic tests
Fixed `ArrayOfLowCardinality.InsertAndQuery` if `backward_compatibility_lowcardinality_as_wrapped_column` is false
=> Various test fixes

clickhouse/CMakeLists.txt
install `server_exception.h`
closes: #198
=> update cmake and install newly server_exception.h

clickhouse/columns/string.cpp, clickhouse/columns/string.h, ut/columns_ut.cpp
[https://github.com/ClickHouse/clickhouse-cpp/issues/197](url)
=> optimize ColumnString Append

clickhouse/columns/factory.cpp, ut/types_ut.cpp
`case TypeAst::Enum` in `CreateColumnFromAst `  has bug when `ast.elements.size() ==1`
=> fix CreateColumnFromAst

clickhouse/base/socket.cpp, clickhouse/base/socket.h, clickhouse/base/sslsocket.cpp, clickhouse/base/sslsocket.h, clickhouse/client.h, ut/socket_ut.cpp
When I was working with the library, I found the following behavior: when my application is connecting to the clickhouse server, it may stick forever due to connection problems.
A connection to the server can be established, but nothing can be read from the socket because you try to connect to another running application in your system. 
For resolving this problem I added receive and send timeouts to socket.
=> Add recv/send timeouts to socket

README.md
- This issue is to correct the example codes and it's described in this [comment](https://github.com/ClickHouse/clickhouse-cpp/issues/214#issuecomment-1268116484) clearly.
=> Correct example codes

clickhouse/base/socket.cpp
Added a RAII wrapper around raw SOCKET to perform proper cleanup in case of exception or retry.
Closes: #208
=> Socket RAII wrapper to prevent leaking socket

clickhouse/block.cpp, clickhouse/block.h, clickhouse/client.cpp, clickhouse/query.h, ut/client_ut.cpp
I want to implement supporting query parameters. It requires raising the version of the protocol. The gap between the current server version of the protocol and the current client library version of the protocol is huge for one PR. So I decided to create several small PR and raise versions step by step.
=> Support client write info 

clickhouse/base/socket.cpp
`FormatMessage` expects like `FormatMessageW` a wide char array. See https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-formatmessage and https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-formatmessagew for more information.
Using `FormatMessage` with a normal char array leads to a build failure on UWP:
```
D:\buildtrees\clickhouse-cpp\src\v2.2.1-26f006ec81.clean\clickhouse\base\socket.cpp(30): error C2664: 'DWORD FormatMessageW(DWORD,LPCVOID,DWORD,DWORD,LPWSTR,DWORD,va_list *)': cannot convert argument 5 from 'char [255]' to 'LPWSTR'
D:\buildtrees\clickhouse-cpp\src\v2.2.1-26f006ec81.clean\clickhouse\base\socket.cpp(30): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast …
```
=> Use `FormatMessageA`

clickhouse/client.cpp, clickhouse/query.h, ut/client_ut.cpp
I would like to suggest the implementation of per-query settings.  First of all, I refuse to support binary settings serialization because it is deprecated since server version 19.18.   The implementation is based on the following ideas 
1. Use compiled checked settings names and values (especially for enums). It will protect from mistyping.
2. Easy synchronization settings list with server source code.  That's why settings, menus, and defaults are just copy-pasted from server sources. All macros have the same syntax.
3. Settings have to be sent only if they have been set. No data is transmitted by default.  
4. Object QuerrySettings is light and easy to reuse in different queries. It contains unordered_map of string views of static names. So it allocate memory only for values.
=> Implementation per query settings

clickhouse/columns/string.cpp
Platform: windows
Data: 100w,  10w/per
This is a bug for batch write.  It costs too much cpu time.
Before remove, already cost 1min and nothing insert ok. Top hot:
After remove, just cost 18.7s and all insert ok. Top hot:
=> bugfix, remove items_.reserve for batch write

clickhouse/columns/string.cpp, clickhouse/columns/string.h
By estimating the total element count, code like this:
```c++
constexpr size_t total = 100000;
for (int i = 0; i < 10; i++) {
clickhouse::Block block;
auto a_ptr = std::make_shared<clickhouse::ColumnInt32>();
auto b_ptr = std::make_shared<clickhouse::ColumnUInt64>();
auto c_ptr = std::make_shared<clickhouse::ColumnString>(total);
auto d_ptr = std::make_shared<clickhouse::ColumnArray>(std::make_shared<clickhouse::ColumnString>(total * 3));
auto e_ptr = std::make_shared<clickhouse::ColumnArray>(
std::make_shared<clickhouse::ColumnArray>(
std::make_shared<clickhouse::ColumnString>(total * 3 * 4)));
...
```
Before estimating, total time(18720), network time(7353), other time(18720-7353=11367),  top hot:
After estimating, total time(15728), network time(7317) _**same as above(7353)**_, other …
=> ColumnString improve performance(26%) by avoiding vector reallocate

README.md, clickhouse/CMakeLists.txt, clickhouse/client.h, clickhouse/columns/array.h, clickhouse/columns/factory.cpp, clickhouse/columns/itemview.cpp, clickhouse/columns/map.cpp, clickhouse/columns/map.h, clickhouse/columns/tuple.h, clickhouse/columns/utils.h, clickhouse/types/type_parser.cpp, clickhouse/types/type_parser.h, clickhouse/types/types.cpp, clickhouse/types/types.h, ut/client_ut.cpp, ut/columns_ut.cpp, ut/itemview_ut.cpp, ut/type_parser_ut.cpp, ut/types_ut.cpp, ut/utils.cpp, ut/utils.h
This type described  here 
https://clickhouse.com/docs/en/sql-reference/data-types/map
=> Support column type: map

ut/client_ut.cpp, ut/ssl_ut.cpp
Looks like `filesystemFree()` is not supported on `explorer@play.clickhouse.com:9440` endpoint anymore
=> Removed SELECT statement that is not supported on some remote endpoints

.github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/windows_mingw.yml, .github/workflows/windows_msvc.yml
To make sure that CI/CD is always up-to-date and nothing is broken due to stale dependencies
=> Scheduling CI/CD runs on Monday midnight

clickhouse/columns/tuple.h
- Added get value at function, along with operator [].
Reason:
The current implement operator [] does not work in Objective-C, so adding the ->At().
Update:
Sorry, my bad, it works with the syntax:  
``` 
auto cols = tup->operator[](c); 
````
but it's a bit ugly IMO.
=> Support get value at.

README.md, clickhouse/CMakeLists.txt, clickhouse/client.h, clickhouse/columns/factory.cpp, clickhouse/columns/geo.cpp, clickhouse/columns/geo.h, clickhouse/columns/tuple.h, clickhouse/types/type_parser.cpp, clickhouse/types/types.cpp, clickhouse/types/types.h, ut/client_ut.cpp, ut/types_ut.cpp, ut/utils.cpp
Support types described there
https://clickhouse.com/docs/en/sql-reference/data-types/geo
=> Support geo column types

clickhouse/columns/lowcardinality.cpp, ut/low_cardinality_nullable_tests.cpp
`ColumnLowCardinality::Load` allocate the wrong amount rows for `LowCardinality(Nullable(X))` columns. In most cases, it leads to extra memory allocation than required. But in case then the number of rows in a column is less than the dictionary size exception "`can't load column 'some column' of type LowCardinality(Nullable(X))`" happened. The dictionary always contains null and default values. So if the column contains every unique value once and doesn't contain a null or default value, then such a situation happens.
=> fix bug in ColumnLowCardinality::Load

clickhouse/columns/array.cpp, ut/client_ut.cpp
If column Array(Low Cardinality(T)) contains only empty arrays Save/Load methods don't work properly.
=> fix bug with load/save Array with empty arrays

clickhouse/columns/factory.cpp, clickhouse/types/type_parser.cpp, ut/CreateColumnByType_ut.cpp, ut/client_ut.cpp, ut/type_parser_ut.cpp, ut/types_ut.cpp
Implemented safer access to the ast elements.
Fixed parsing empty type name (or with whitespace only) as valid AST, now it produces error.
Fixes #266
=> Fix crash on invalid AST

clickhouse/base/socket.cpp, clickhouse/base/socket.h, clickhouse/base/sslsocket.cpp, clickhouse/client.h, ut/socket_ut.cpp
Following up on #205, it would be nice to have control over the connection timeout as well.
Currently it is limited at 5 seconds regardless of configured recv/send timeouts.
=> Add connect timeout to socket

clickhouse/base/socket.cpp, clickhouse/base/socket.h, ut/socket_ut.cpp
`getaddrinfo` error reporting is currently broken on non-Windows platforms as only a subset of its errors are reported via `errno`.
(On Windows everything gets combined in `WSAGetLastError()` and `gai_strerror` is declared not thread-safe for some reason.)
=> Fix getaddrinfo error reporting

CMakeLists.txt, clickhouse/CMakeLists.txt, tests/simple/CMakeLists.txt, ut/CMakeLists.txt
Introduce separating building static and shared libs, depends on cmake out-of-the-box option BUILD_SHARED_LIBS https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html. Also creates alias target for transparently linking to static or shared lib.
=> Separate building static and shared libs

clickhouse/types/type_parser.cpp, ut/CreateColumnByType_ut.cpp, ut/client_ut.cpp
Bool table columns are not recognized and mapped to "Void".
Mapping updated to treat Bool columns as UInt8
=> Handle "Bool" columns

README.md
=> Dependecies info

README.md
=> Expand application tutorial

clickhouse/query.h, ut/utils.cpp, ut/utils.h
https://github.com/ClickHouse/clickhouse-cpp/actions/runs/4714567769/jobs/8361003596?pr=298
```
D:\a\clickhouse-cpp\clickhouse-cpp\ut\utils.h(120,16): error C2679: binary '<<': no operator found which takes a right-hand operand of type 'const _Ty' (or there is no acceptable conversion) [D:\a\clickhouse-cpp\clickhouse-cpp\build\ut\clickhouse-cpp-ut.vcxproj]
with
[
_Ty=clickhouse::Profile
]
```
=> Fix Windows build

clickhouse/columns/lowcardinalityadaptor.h
Should've been deprecated together with [`backward_compatibility_lowcardinality_as_wrapped_column`](https://github.com/ClickHouse/clickhouse-cpp/blob/master/clickhouse/client.h#L106) by #233
=> Minor: Deprecated LowCardinalitySerializationAdaptor

CMakeLists.txt, cmake/Findlz4.cmake
That prints some info about dependencies both at configure and at compile time.
Shouldn't affect produced binaries, just a little utility to help debugging third-party issues.
=> added DEBUG_DEPENDENCIES

clickhouse/columns/string.cpp
- made it more thread-safe (`blocks_` and `items_` are always either fully updated or not changed at all)
- removed piece of code that confused lots of static analyzers (false positive on dereferencing nullptr-`block` variable)
fixes #307
=> Updated ColumnString::LoadBody

cmake/Findcityhash.cmake
cityhash does not provide any CMake packages. Add a `Findcityhash.cmake` script to help find cityhash.
=> Fix system cityhash setup

clickhouse/client.cpp, ut/CMakeLists.txt, ut/abnormal_column_names_test.cpp, ut/abnormal_column_names_test.h, ut/client_ut.cpp
Fix abnormal column names in gcc7.3.1
example: "select 123,231,113"
on gcc7.3.1 output:
name:113, type:UInt8
name:113, type:UInt8
name:113, type:UInt8
on gcc9.3.1 output:
name:123, type:UInt8
name:231, type:UInt8
name:113, type:UInt8
=> Fix abnormal column names in gcc7.3.1

clickhouse/columns/enum.cpp, clickhouse/columns/enum.h
The `ColumnEnum<T>` can be initialized with `std::vector<T>` by moving the vector instead of copying.
=> Add move semantics for ColumnEnum

clickhouse/CMakeLists.txt
update cmake and install newly endpoints_iterator.h
=> update cmake and install newly endpoints_iterator.h

.github/workflows/macos.yml, .github/workflows/windows_mingw.yml, .github/workflows/windows_msvc.yml
Disabled tests that rely on some privileges that might be unavailable on a remote server:
- Client/ClientCase.Query_ID
- Client/ClientCase.TracingContext
=> Less flaky tests when executing against remote server (not docker)

clickhouse/CMakeLists.txt, clickhouse/columns/date.cpp, clickhouse/columns/date.h, clickhouse/columns/decimal.h, clickhouse/columns/enum.cpp, clickhouse/columns/enum.h, clickhouse/columns/geo.cpp, clickhouse/columns/geo.h, clickhouse/columns/map.h, clickhouse/columns/nothing.h, clickhouse/columns/numeric.cpp, clickhouse/columns/numeric.h, clickhouse/columns/string.cpp, clickhouse/columns/string.h, clickhouse/columns/tuple.h, clickhouse/columns/uuid.cpp, clickhouse/columns/uuid.h, ut/Column_ut.cpp, ut/columns_ut.cpp, ut/performance_tests.cpp, ut/roundtrip_tests.cpp, ut/utils_comparison.h, ut/utils_meta.h, ut/utils_ut.cpp, ut/value_generators.cpp, ut/value_generators.h
Provide an interface for writing/reading immediate values for `Date` and `Date32` columns without conversion.
Closes: #318
=> Implemented Append/RawAt/operator[] for ColumnDate and ColumnDate32 that work with uint16_t/int32_t

clickhouse/client.cpp, clickhouse/columns/string.cpp, ut/client_ut.cpp, ut/roundtrip_column.h
Due to setting `ClientOptions.SetSendRetries(0)`, Client made no attempts to connect to a server, which resulted in uninitialized streams and hence the crash.
Closes: #335
=> Fixed issue #335 by making at least one connection attempt

clickhouse/columns/date.cpp, clickhouse/columns/date.h, clickhouse/columns/ip4.cpp, clickhouse/columns/ip4.h, ut/columns_ut.cpp
These constructors can be valuable for enhancing performance in scenarios where a user knows the row count and can preallocate memory.
I also considered adding a similar constructor for `ColumnDateTime`, but its public interface exclusively utilizes `time_t`, while `uint32_t` is an implementation detail. I'm unsure if extending the interface with implementation details would be a good idea.
=> Add rvalue vector ctors for ColumnDate, ColumnDate32 and ColumnIPv4

clickhouse/types/types.cpp
`std::memory_order::memory_order_relaxed` syntax is invalid in `-std=c++20`.
See:
https://en.cppreference.com/w/cpp/atomic/memory_order
https://github.com/llvm/llvm-project/blob/main/libcxx/include/__atomic/memory_order.h
=> Fix memory_order syntax

clickhouse/columns/array.h, clickhouse/columns/string.cpp, ut/column_array_ut.cpp
Optimize `ColumnArrayT::Append()` to allow underlying column (e.g. `ColumnString`) to 'steal' values if it has r-value overload of `Append()` to prevent excessive copying.
=> ColumnArrayT Append will move container data if it is right value

clickhouse/columns/date.cpp, clickhouse/columns/date.h
`AppendRaw()` already exists for `ColumnDateTime`, but `RawAt()` doesn't.
=> Add RawAt() for ColumnDateTime

README.md
add explain for Asynchronous inserts
=> add explain for Asynchronous inserts

CMakeLists.txt, clickhouse/CMakeLists.txt
The Clang workaround is preventing me from building. Already using inteldfp and the symbols conflict with gcc_s
removing this block (or enabling the disable flag provided here) Solves this issue and preserves functionality for issues requiring it
Clang 19.1.3
Rocky Linux 9.4
=> add option to disable the workaround enabled for clang + libstdc++

clickhouse/base/output.cpp
@Enmk These are additional corrections necessary for the correct operation of the changes implemented in the PR #407. Implement resend when performing a flash on a buffered output. Please check.
=> Implemented resending of data when performing a flash in buffered output

clickhouse/base/wire_format.cpp, clickhouse/base/wire_format.h, clickhouse/client.cpp, clickhouse/query.h, tests/simple/main.cpp, ut/client_ut.cpp
- **params**
- **Nullable params**
=> Parameters in clickhouse-cpp

ut/low_cardinality_nullable_tests.cpp
Test for a deprecated feature, which is going to be removed anyway
=> Disabled LowCardinalityOfNullable.ThrowOnBackwardsCompatibleLCColumn

clickhouse/CMakeLists.txt
Resolves #408 
To check:
```shell
$ cmake -S . -B build -DCMAKE_INSTALL_PREFIX=/usr/local
$ cmake --build build
$ cmake --install install
```
It installs:
```
-- Install configuration: "RelWithDebInfo"
-- Installing: /usr/local/lib/libclickhouse-cpp-lib.a
-- Installing: /usr/local/lib/libcityhash.a
-- Installing: /usr/local/lib/liblz4.a
-- Installing: /usr/local/lib/libzstdstatic.a
-- Installing: /usr/local/lib/libabsl_int128.a
```
=> Install contrib libraries

clickhouse/client.cpp, clickhouse/exceptions.h
By
https://en.cppreference.com/w/cpp/error/exception
Each standard library class T that derives from std::exception has the following publicly accessible member functions, each of them do not exit with an exception(until C++11)having a [non-throwing exception specification](https://en.cppreference.com/w/cpp/language/noexcept_spec)(since C++11): copy_constructor
For copy unique_ptr we must allocate new space and copy object into one. The allocation can throw exception. So we cannot use unique_ptr.
I change it to shared_ptr that works without memory allocation in copy constructor.
=> Using shared_ptr in exception class

clickhouse/columns/ip4.cpp, clickhouse/columns/ip6.cpp
const auto& addr = this->At(n);
auto tmp_addr = addr;
the line auto tmp_addr = addr; creates a copy of the object referred to by addr. This copy, tmp_addr, is not marked as const even though addr is a constant reference. As a result, the address of tmp_addr (i.e., &tmp_addr) is of a non-const pointer type, which is acceptable for the inet_ntop function.
Passing &tmp_addr to inet_ntop solves the issue of an invalid conversion from const void* to void*, because &tmp_addr is now of the type void* (or can be implicitly converted to it), bypassing the compiler error that would occur if you tried to pass directly &addr.
This approach is valid provided that this->At(n) returns the data in a way that allows creating a copy with auto tmp_addr without any unintended side effects.
=> Fix MinGW Compiling Error

README.md, clickhouse/client.cpp, clickhouse/client.h
Support for external data on SELECT requests, see https://clickhouse.com/docs/engines/table-engines/special/external-data
=> Support for external data

README.md, clickhouse/base/uuid.h, clickhouse/columns/factory.cpp, clickhouse/columns/itemview.cpp, clickhouse/columns/itemview.h, clickhouse/columns/numeric.cpp, clickhouse/columns/numeric.h, clickhouse/types/type_parser.cpp, clickhouse/types/types.cpp, clickhouse/types/types.h, ut/Column_ut.cpp, ut/CreateColumnByType_ut.cpp, ut/columns_ut.cpp, ut/value_generators.cpp, ut/value_generators.h
Added UInt128 support. Closes https://github.com/ClickHouse/clickhouse-cpp/issues/378
Tiny backward-incompatible change: UUID type was previously declared by using UInt128 declaration not compatible with the absl one, so the UUID declaration has been changed to remain internally the same but UInt128 has been redeclared by using absl::uint128.
=> Support UInt128 type

clickhouse/columns/array.cpp
The ColumnArray constructor would just accept incompatible value- and
offset-arrays and the client would then happily send them, causing
issues in the ClickHouse server.
This introduces validation of the arrays.
Fixes https://github.com/ClickHouse/clickhouse-cpp/issues/426
=> Introduce validation to the ColumnArray constructor
